baseURL = "https://carapacik.github.io/"
title = "Carapacik"
theme = "PaperMod"

[languages.en]
languageName = "English"
[[languages.en.menu.main]]
identifier = "posts"
name = "Blog"
url = "/posts/"
weight = 10

[[languages.en.menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects/"
weight = 20

[languages.en.params.profileMode]
enabled = true
title = "Roman Laptev"
subtitle = "Flutter developer"

[[languages.en.params.profileMode.buttons]]
name = "Blog"
url = "/posts/"

[[languages.en.params.profileMode.buttons]]
name = "Projects"
url = "/projects/"

[languages.ru]
languageName = "Russian"

[[languages.ru.menu.main]]
identifier = "posts"
name = "Блог"
url = "/posts/"
weight = 10

[[languages.ru.menu.main]]
identifier = "projects"
name = "Проекты"
url = "/projects/"
weight = 20

[languages.ru.params.profileMode]
enabled = true
title = "Роман Лаптев"
subtitle = "Flutter разработчик"

[[languages.ru.params.profileMode.buttons]]
name = "Блог"
url = "/ru/posts/"

[[languages.ru.params.profileMode.buttons]]
name = "Проекты"
url = "/ru/projects/"


[params]
env = "production"
author = "Carapacik"
ShowReadingTime = true
ShowShareButtons = true
ShowRssButtonInSectionTermList = true

[[params.socialIcons]]
name = "telegram"
url = "https://carapacik.t.me"

[[params.socialIcons]]
name = "github"
url = "https://github.com/Carapacik"

[[params.socialIcons]]
name = "email"
url = "mailto://carapacik@gmail.com"
