baseURL = "https://carapacik.github.io/"
languageCode = "en-us"
title = "Carapacik"
theme = "PaperMod"

[[menu.main]]
identifier = "posts"
name = "Blog"
url = "/posts"
weight = 10

[[menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects"
weight = 20

[params]
ShowReadingTime = true

[params.profileMode]
enabled = true
title = "Roman Laptev"
subtitle = "Flutter developer"

[[params.profileMode.buttons]]
name = "Blog"
url = "/posts"

[[params.profileMode.buttons]]
name = "Projects"
url = "/projects"

[[params.socialIcons]]
name = "telegram"
url = "https://carapacik.t.me"

[[params.socialIcons]]
name = "github"
url = "https://github.com/Carapacik"

[[params.socialIcons]]
name = "email"
url = "mailto:carapacik@gmail.com"


